### ISSUE TITLE
Sourcemap file not generated

### ISSUE THREAD

**Issue by daanvosdewael** [sass/sassc#202]
When compiling with the `--sourcemap` flag, only the `sourceMappingURL` is added to the output file. The `.css.map` file is not generated.

```bash
$ sassc -v
sassc: 3.4.0
libsass: 3.4.0
sass2scss: 1.1.0
sass: 3.4
```

**Comment by am11** [comment]
Thanks for the report @daanvosdewael. I can reproduce this issue.

@mgreter, with this patch:

```diff
diff --git a/sassc.c b/sassc.c
index 9e75945..ff1aa24 100644
--- a/sassc.c
+++ b/sassc.c
@@ -150,12 +150,12 @@ int compile_file(struct Sass_Options* options, char* input_path, char* outfile)
         outfile
     );

-    if (ret == 0 && sass_option_get_source_map_file(options)) {
+    if (ret == 0 && sass_option_get_source_map_file(ctx_out)) {
         ret = output(
             sass_context_get_error_status(ctx_out),
             sass_context_get_error_message(ctx_out),
             sass_context_get_source_map_string(ctx_out),
-            sass_option_get_source_map_file(options)
+            sass_option_get_source_map_file(ctx_out)
         );
     }
```

this issue gets fixed, but instead shouldn't all the `sass_option_get_*` methods work with `options` object instead of context?

Also, we should probably avoid calling `sass_option_get_source_map_file` twice (`char* map_file =  sass_option_get_source_map_file(ctx_out);` before the `if` block).

**Comment by mgreter** [comment]
@am11 thanks for looking into this. I believe this got introduced with https://github.com/sass/libsass/pull/2213. But your change make sense! Sass_Context [is also](https://github.com/sass/libsass/blob/master/src/sass_context.hpp#L70) in itself a Sass_Options struct (it inherits from it). So what we do in sassc is that we create an option struct merely to initialize the context later, so we can re-use it for data and for file contexts/compilers. So basically we copy the options from `options` to `ctx_out`. Since options can link to memory we need to free later, we now reset (consume) the options when `sass_file_context_set_options` is called. I guess we could leave certain properties alone if we don't free them later, but I think it doesn't really mater as using `ctx_out` in the above case feels more correct anyway. Hope this makes sense. Previousely we had a minor memory leak with options and I don't see another easy way to fix this.

BTW. I don't see a problem with calling `sass_option_get_source_map_file` twice. Would be a different story if you'd call `sass_option_take_XYZ` twice :)

**Comment by am11** [comment]
Thanks for the clarification @mgreter! I have opened #203 with the fix. :)

**Comment by mgreter** [comment]
@am11 actually that does seem to give an expected warning (I actually wondered why you did not hit that, but I thought it would error): `incompatible types - from 'Sass_Context *' to 'Sass_Options *'`

Anyway, this fix is rather easy (I have to admit it looks a bit dodgy):

```diff
sass_file_context_set_options(ctx, options);
+ options = sass_file_context_get_options(ctx);
```

Of course we could also just do `const char* srcmap_file = sass_option_get_source_map_file(ctx_out)` before calling `sass_file_context_set_options` and use that in the later check.

**Comment by am11** [comment]
@mgreter, I got that warning too. I have changed it so we get the `srcmap_file` with `options` before consuming the options. Now there is no warning. Does it looks good?

> just a pitty that we cannot tell the compiler that these structs actually inherit without exposing the complete implementation too. https://github.com/sass/libsass/blob/master/src/sass_context.cpp#L645

Agree that would be a nice cpp->c interoperability. :)

**Comment by daanvosdewael** [comment]
@am11 @mgreter Thanks guys!
